import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, team, analytics
}: {
  children: React.ReactNode,
  team: React.ReactNode,
  analytics: React.ReactNode
}) {
  return (
    <div>
      <h1>Layout of dashboard and setting</h1>
      {children}
      {team}
      {analytics}
    </div>
  )
}
